[build-system]
requires = ["setuptools", "wheel"]

[project]
name = "supercalc"
version = "0.0.1"
authors = [{ name = "Bjoern" }]
readme = "Readme.md"

dependencies = []

[project.scripts]
"suca" = "supercalc.main:main"

[tool.setuptools]
packages = ["supercalc"]

[tool.black]
line-length = 100
